```python
Xtr, Ytr, Xte, Yte = load_CIFAR10('data/cifar10/') # a magic function we provide
# flatten out all images to be one-dimensional
Xtr_rows = Xtr.reshape(Xtr.shape[0], 32 * 32 * 3) # Xtr_rows becomes 50000 x 3072
Xte_rows = Xte.reshape(Xte.shape[0], 32 * 32 * 3) # Xte_rows becomes 10000 x 3072
```
Xtr.shape输出一元数组 第零个是50000

In [12]:
import numpy as np

c=5
Xtr=np.zeros((c,32,32,3))
print(Xtr[0].shape)
print(Xtr.shape)
print(Xtr.shape[0]) 
y=Xtr.reshape( c,32*32*3)
print(y)

(32, 32, 3)
(5, 32, 32, 3)
5
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


```python
distances = np.sum(np.abs(self.Xtr - X[i,:]), axis = 1)
```
self.Xtr - X[i,:] 得到一个二维数组，每一行是一个训练样本与测试样本的差值。

np.abs(...) 取绝对值。

np.sum(..., axis=1) 表示对每一行的所有元素求和，得到每个训练样本与测试样本的距离（每行变成一个数）。

In [13]:

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


```python
print 'accuracy: %f' % ( np.mean(ans_Yte == Yte) )
```

In [14]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]
